trigger:
  branches:
    include:
      - master

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

jobs:
- job: macos
  pool:
    vmImage: macos-10.14
  steps:
    - script: './setup_macos.sh'
    - script: './build-qt-wallet-macos.sh'
    - script: './deploy_macos.sh'
  displayName: 'MacOSX'
- job: windows32
  pool:
    vmImage: windows-latest
  steps:
    - script: 'setup_windows32.bat'
    - script: 'build-qt-wallet-windows32.bat'
    - script: 'deploy_windows32.bat'
  displayName: 'Windows32'
